In [1]:
# Supress Warnings
import warnings
warnings.filterwarnings('ignore')

# Data Science
import pandas as pd
import numpy as np

# Machine Learning
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

#Others
import joblib

In [2]:
df = pd.read_csv('2011-2022_mergedcrimerate.csv')
df.head()

,Month,LSOA code,Count,Population,Pop_density,IMD Score,Income Score,IDACI Score,IDAOPI Score,Employment Score,...,Crime Score,BHS Score,GB Score,WB Score,LE Score,Indoors Score,Outdoors Score,Inflation_rate,unemployment_rate,Crime Rate
0,2011-01,E01007599,1,1760.0,15.6031,11.20,0.07,0.07,0.13,0.06,...,0.01,30.71,55.81,5.61,6.45,6.13,7.09,3.4,7.8,0.9
1,2011-01,E01007609,2,2302.0,17.9576,18.22,0.13,0.13,0.22,0.10,...,0.65,15.76,21.48,10.04,9.33,9.86,8.27,3.4,7.8,1.3
2,2011-01,E01013810,6,1657.0,0.1345,39.59,0.29,0.42,0.44,0.13,...,1.23,17.42,1.25,33.59,34.51,26.90,49.74,3.4,7.8,5.4
3,2011-01,E01013811,26,1446.0,0.1280,45.17,0.27,0.41,0.58,0.16,...,1.99,17.77,0.22,35.31,36.36,33.08,42.91,3.4,7.8,27.0
4,2011-01,E01013812,19,1617.0,0.1209,47.45,0.36,0.55,0.45,0.16,...,1.78,18.06,0.17,35.94,31.94,18.63,58.57,3.4,7.8,17.6

In [3]:
model = joblib.load('rf_crimerate_final.pkl')

In [4]:
df = df.drop(['Month', 'LSOA code', 'Count', 'AS Score', 'Inflation_rate', 'Indoors Score'], axis=1)
df.head()

,Population,Pop_density,IMD Score,Income Score,IDACI Score,IDAOPI Score,Employment Score,EST Score,CYP Score,HDD Score,Crime Score,BHS Score,GB Score,WB Score,LE Score,Outdoors Score,unemployment_rate,Crime Rate
0,1760.0,15.6031,11.20,0.07,0.07,0.13,0.06,7.63,5.13,-0.33,0.01,30.71,55.81,5.61,6.45,7.09,7.8,0.9
1,2302.0,17.9576,18.22,0.13,0.13,0.22,0.10,15.40,9.68,0.22,0.65,15.76,21.48,10.04,9.33,8.27,7.8,1.3
2,1657.0,0.1345,39.59,0.29,0.42,0.44,0.13,40.88,53.40,1.11,1.23,17.42,1.25,33.59,34.51,49.74,7.8,5.4
3,1446.0,0.1280,45.17,0.27,0.41,0.58,0.16,48.27,75.49,1.24,1.99,17.77,0.22,35.31,36.36,42.91,7.8,27.0
4,1617.0,0.1209,47.45,0.36,0.55,0.45,0.16,55.18,78.70,0.92,1.78,18.06,0.17,35.94,31.94,58.57,7.8,17.6

In [5]:
X = df.drop(columns=['Crime Rate']).values
y = df['Crime Rate'].values
# Choose any random state
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=17)

In [6]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_pred = sc.transform(X)

In [7]:
prediction = model.predict(X_pred)

In [8]:
prediction[0:25]

array([ 3.84705226,  4.56903761,  8.82508516, 23.31345456, 14.45098604,
       19.42248623, 17.57215179, 35.00593456, 53.07632214, 11.37619229,
       13.8779937 , 11.04049698, 13.74429915, 15.37329671, 19.06686017,
       10.98237108,  7.17301991, 13.15841689, 12.61901507, 10.95027436,
        9.05916366, 13.80228079,  8.58305795,  5.58728044, 12.46617239])

In [10]:
df_pred = pd.DataFrame(prediction)
df_pred.columns = ['rf_pred']

In [11]:
df_pred.to_csv('rf_prediction.csv', index=False)